---
require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 140

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 17

Style/SignalException:
  Enabled: false

Style/NumberedParametersLimit:
  Enabled: false

Style/CaseEquality:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
